name: IRS Reduction Threshold Upper Benchmark

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  irs-reduction-threshold-upper:
    uses: ./.github/workflows/benchmark.yml
    with:
      profile: upper
